<?php

use \Illuminate\Database\Seeder;
use Tenderos\Entities\Municipality;

class MunicipalitiesTableSeeder extends Seeder
{
	private $municipalitiesArray = [
		['deparment_id' => 5, 'cod' => 1, 'name' =>	'medellin'],
		['deparment_id' => 5, 'cod' => 2, 'name' =>	'abejorral'],
		['deparment_id' => 5, 'cod' => 4, 'name' =>	'abriaqui'],
		['deparment_id' => 5, 'cod' => 21, 'name' =>	'alejandria'],
		['deparment_id' => 5, 'cod' => 30, 'name' =>	'amaga'],
		['deparment_id' => 5, 'cod' => 31, 'name' =>	'amalfi'],
		['deparment_id' => 5, 'cod' => 34, 'name' =>	'andes'],
		['deparment_id' => 5, 'cod' => 36, 'name' =>	'angelopolis'],
		['deparment_id' => 5, 'cod' => 38, 'name' =>	'angostura'],
		['deparment_id' => 5, 'cod' => 40, 'name' =>	'anori'],
		['deparment_id' => 5, 'cod' => 42, 'name' =>	'santafe de antioquia'],
		['deparment_id' => 5, 'cod' => 44, 'name' =>	'anza'],
		['deparment_id' => 5, 'cod' => 45, 'name' =>	'apartado'],
		['deparment_id' => 5, 'cod' => 51, 'name' =>	'arboletes'],
		['deparment_id' => 5, 'cod' => 55, 'name' =>	'argelia'],
		['deparment_id' => 5, 'cod' => 59, 'name' =>	'armenia'],
		['deparment_id' => 5, 'cod' => 79, 'name' =>	'barbosa'],
		['deparment_id' => 5, 'cod' => 86, 'name' =>	'belmira'],
		['deparment_id' => 5, 'cod' => 88, 'name' =>	'bello'],
		['deparment_id' => 5, 'cod' => 91, 'name' =>	'betania'],
		['deparment_id' => 5, 'cod' => 93, 'name' =>	'betulia'],
		['deparment_id' => 5, 'cod' => 101, 'name' =>	'ciudad bolivar'],
		['deparment_id' => 5, 'cod' => 107, 'name' =>	'briceño'],
		['deparment_id' => 5, 'cod' => 113, 'name' =>	'buritica'],
		['deparment_id' => 5, 'cod' => 120, 'name' =>	'caceres'],
		['deparment_id' => 5, 'cod' => 125, 'name' =>	'caicedo'],
		['deparment_id' => 5, 'cod' => 129, 'name' =>	'caldas'],
		['deparment_id' => 5, 'cod' => 134, 'name' =>	'campamento'],
		['deparment_id' => 5, 'cod' => 138, 'name' =>	'cañasgordas'],
		['deparment_id' => 5, 'cod' => 142, 'name' =>	'caracoli'],
		['deparment_id' => 5, 'cod' => 145, 'name' =>	'caramanta'],
		['deparment_id' => 5, 'cod' => 147, 'name' =>	'carepa'],
		['deparment_id' => 5, 'cod' => 148, 'name' =>	'el carmen de viboral'],
		['deparment_id' => 5, 'cod' => 150, 'name' =>	'carolina'],
		['deparment_id' => 5, 'cod' => 154, 'name' =>	'caucasia'],
		['deparment_id' => 5, 'cod' => 172, 'name' =>	'chigorodo'],
		['deparment_id' => 5, 'cod' => 190, 'name' =>	'cisneros'],
		['deparment_id' => 5, 'cod' => 197, 'name' =>	'cocorna'],
		['deparment_id' => 5, 'cod' => 206, 'name' =>	'concepcion'],
		['deparment_id' => 5, 'cod' => 209, 'name' =>	'concordia'],
		['deparment_id' => 5, 'cod' => 212, 'name' =>	'copacabana'],
		['deparment_id' => 5, 'cod' => 234, 'name' =>	'dabeiba'],
		['deparment_id' => 5, 'cod' => 237, 'name' =>	'don matias'],
		['deparment_id' => 5, 'cod' => 240, 'name' =>	'ebejico'],
		['deparment_id' => 5, 'cod' => 250, 'name' =>	'el bagre'],
		['deparment_id' => 5, 'cod' => 264, 'name' =>	'entrerrios'],
		['deparment_id' => 5, 'cod' => 266, 'name' =>	'envigado'],
		['deparment_id' => 5, 'cod' => 282, 'name' =>	'fredonia'],
		['deparment_id' => 5, 'cod' => 284, 'name' =>	'frontino'],
		['deparment_id' => 5, 'cod' => 306, 'name' =>	'giraldo'],
		['deparment_id' => 5, 'cod' => 308, 'name' =>	'girardota'],
		['deparment_id' => 5, 'cod' => 310, 'name' =>	'gomez plata'],
		['deparment_id' => 5, 'cod' => 313, 'name' =>	'granada'],
		['deparment_id' => 5, 'cod' => 315, 'name' =>	'guadalupe'],
		['deparment_id' => 5, 'cod' => 318, 'name' =>	'guarne'],
		['deparment_id' => 5, 'cod' => 321, 'name' =>	'guatape'],
		['deparment_id' => 5, 'cod' => 347, 'name' =>	'heliconia'],
		['deparment_id' => 5, 'cod' => 353, 'name' =>	'hispania'],
		['deparment_id' => 5, 'cod' => 360, 'name' =>	'itagui'],
		['deparment_id' => 5, 'cod' => 361, 'name' =>	'ituango'],
		['deparment_id' => 5, 'cod' => 364, 'name' =>	'jardin'],
		['deparment_id' => 5, 'cod' => 368, 'name' =>	'jerico'],
		['deparment_id' => 5, 'cod' => 376, 'name' =>	'la ceja'],
		['deparment_id' => 5, 'cod' => 380, 'name' =>	'la estrella'],
		['deparment_id' => 5, 'cod' => 390, 'name' =>	'la pintada'],
		['deparment_id' => 5, 'cod' => 400, 'name' =>	'la union'],
		['deparment_id' => 5, 'cod' => 411, 'name' =>	'liborina'],
		['deparment_id' => 5, 'cod' => 425, 'name' =>	'maceo'],
		['deparment_id' => 5, 'cod' => 440, 'name' =>	'marinilla'],
		['deparment_id' => 5, 'cod' => 467, 'name' =>	'montebello'],
		['deparment_id' => 5, 'cod' => 475, 'name' =>	'murindo'],
		['deparment_id' => 5, 'cod' => 480, 'name' =>	'mutata'],
		['deparment_id' => 5, 'cod' => 483, 'name' =>	'nariño'],
		['deparment_id' => 5, 'cod' => 490, 'name' =>	'necocli'],
		['deparment_id' => 5, 'cod' => 495, 'name' =>	'nechi'],
		['deparment_id' => 5, 'cod' => 501, 'name' =>	'olaya'],
		['deparment_id' => 5, 'cod' => 541, 'name' =>	'peðol'],
		['deparment_id' => 5, 'cod' => 543, 'name' =>	'peque'],
		['deparment_id' => 5, 'cod' => 576, 'name' =>	'pueblorrico'],
		['deparment_id' => 5, 'cod' => 579, 'name' =>	'puerto berrio'],
		['deparment_id' => 5, 'cod' => 585, 'name' =>	'puerto nare'],
		['deparment_id' => 5, 'cod' => 591, 'name' =>	'puerto triunfo'],
		['deparment_id' => 5, 'cod' => 604, 'name' =>	'remedios'],
		['deparment_id' => 5, 'cod' => 607, 'name' =>	'retiro'],
		['deparment_id' => 5, 'cod' => 615, 'name' =>	'rionegro'],
		['deparment_id' => 5, 'cod' => 628, 'name' =>	'sabanalarga'],
		['deparment_id' => 5, 'cod' => 631, 'name' =>	'sabaneta'],
		['deparment_id' => 5, 'cod' => 642, 'name' =>	'salgar'],
		['deparment_id' => 5, 'cod' => 647, 'name' =>	'san andres de cuerquia'],
		['deparment_id' => 5, 'cod' => 649, 'name' =>	'san carlos'],
		['deparment_id' => 5, 'cod' => 652, 'name' =>	'san francisco'],
		['deparment_id' => 5, 'cod' => 656, 'name' =>	'san jeronimo'],
		['deparment_id' => 5, 'cod' => 658, 'name' =>	'san jose de la montaña'],
		['deparment_id' => 5, 'cod' => 659, 'name' =>	'san juan de uraba'],
		['deparment_id' => 5, 'cod' => 660, 'name' =>	'san luis'],
		['deparment_id' => 5, 'cod' => 664, 'name' =>	'san pedro'],
		['deparment_id' => 5, 'cod' => 665, 'name' =>	'san pedro de uraba'],
		['deparment_id' => 5, 'cod' => 667, 'name' =>	'san rafael'],
		['deparment_id' => 5, 'cod' => 670, 'name' =>	'san roque'],
		['deparment_id' => 5, 'cod' => 674, 'name' =>	'san vicente'],
		['deparment_id' => 5, 'cod' => 679, 'name' =>	'santa barbara'],
		['deparment_id' => 5, 'cod' => 686, 'name' =>	'santa rosa de osos'],
		['deparment_id' => 5, 'cod' => 690, 'name' =>	'santo domingo'],
		['deparment_id' => 5, 'cod' => 697, 'name' =>	'el santuario'],
		['deparment_id' => 5, 'cod' => 736, 'name' =>	'segovia'],
		['deparment_id' => 5, 'cod' => 756, 'name' =>	'sonson'],
		['deparment_id' => 5, 'cod' => 761, 'name' =>	'sopetran'],
		['deparment_id' => 5, 'cod' => 789, 'name' =>	'tamesis'],
		['deparment_id' => 5, 'cod' => 790, 'name' =>	'taraza'],
		['deparment_id' => 5, 'cod' => 792, 'name' =>	'tarso'],
		['deparment_id' => 5, 'cod' => 809, 'name' =>	'titiribi'],
		['deparment_id' => 5, 'cod' => 819, 'name' =>	'toledo'],
		['deparment_id' => 5, 'cod' => 837, 'name' =>	'turbo'],
		['deparment_id' => 5, 'cod' => 842, 'name' =>	'uramita'],
		['deparment_id' => 5, 'cod' => 847, 'name' =>	'urrao'],
		['deparment_id' => 5, 'cod' => 854, 'name' =>	'valdivia'],
		['deparment_id' => 5, 'cod' => 856, 'name' =>	'valparaiso'],
		['deparment_id' => 5, 'cod' => 858, 'name' =>	'vegachi'],
		['deparment_id' => 5, 'cod' => 861, 'name' =>	'venecia'],
		['deparment_id' => 5, 'cod' => 873, 'name' =>	'vigia del fuerte'],
		['deparment_id' => 5, 'cod' => 885, 'name' =>	'yali'],
		['deparment_id' => 5, 'cod' => 887, 'name' =>	'yarumal'],
		['deparment_id' => 5, 'cod' => 890, 'name' =>	'yolombo'],
		['deparment_id' => 5, 'cod' => 893, 'name' =>	'yondo'],
		['deparment_id' => 5, 'cod' => 895, 'name' =>	'zaragoza'],
		['deparment_id' => 8, 'cod' => 1, 'name' =>	'barranquilla'],
		['deparment_id' => 8, 'cod' => 78, 'name' =>	'baranoa'],
		['deparment_id' => 8, 'cod' => 137, 'name' =>	'campo de la cruz'],
		['deparment_id' => 8, 'cod' => 141, 'name' =>	'candelaria'],
		['deparment_id' => 8, 'cod' => 296, 'name' =>	'galapa'],
		['deparment_id' => 8, 'cod' => 372, 'name' =>	'juan de acosta'],
		['deparment_id' => 8, 'cod' => 421, 'name' =>	'luruaco'],
		['deparment_id' => 8, 'cod' => 433, 'name' =>	'malambo'],
		['deparment_id' => 8, 'cod' => 436, 'name' =>	'manati'],
		['deparment_id' => 8, 'cod' => 520, 'name' =>	'palmar de varela'],
		['deparment_id' => 8, 'cod' => 549, 'name' =>	'piojo'],
		['deparment_id' => 8, 'cod' => 558, 'name' =>	'polonuevo'],
		['deparment_id' => 8, 'cod' => 560, 'name' =>	'ponedera'],
		['deparment_id' => 8, 'cod' => 573, 'name' =>	'puerto colombia'],
		['deparment_id' => 8, 'cod' => 606, 'name' =>	'repelon'],
		['deparment_id' => 8, 'cod' => 634, 'name' =>	'sabanagrande'],
		['deparment_id' => 8, 'cod' => 638, 'name' =>	'sabanalarga'],
		['deparment_id' => 8, 'cod' => 675, 'name' =>	'santa lucia'],
		['deparment_id' => 8, 'cod' => 685, 'name' =>	'santo tomas'],
		['deparment_id' => 8, 'cod' => 758, 'name' =>	'soledad'],
		['deparment_id' => 8, 'cod' => 770, 'name' =>	'suan'],
		['deparment_id' => 8, 'cod' => 832, 'name' =>	'tubara'],
		['deparment_id' => 8, 'cod' => 849, 'name' =>	'usiacuri'],
		['deparment_id' => 11, 'cod' => 1, 'name' =>	'bogota, d.c.'],
		['deparment_id' => 13, 'cod' => 1, 'name' =>	'cartagena'],
		['deparment_id' => 13, 'cod' => 6, 'name' =>	'achi'],
		['deparment_id' => 13, 'cod' => 30, 'name' =>	'altos del rosario'],
		['deparment_id' => 13, 'cod' => 42, 'name' =>	'arenal'],
		['deparment_id' => 13, 'cod' => 52, 'name' =>	'arjona'],
		['deparment_id' => 13, 'cod' => 62, 'name' =>	'arroyohondo'],
		['deparment_id' => 13, 'cod' => 74, 'name' =>	'barranco de loba'],
		['deparment_id' => 13, 'cod' => 140, 'name' =>	'calamar'],
		['deparment_id' => 13, 'cod' => 160, 'name' =>	'cantagallo'],
		['deparment_id' => 13, 'cod' => 188, 'name' =>	'cicuco'],
		['deparment_id' => 13, 'cod' => 212, 'name' =>	'cordoba'],
		['deparment_id' => 13, 'cod' => 222, 'name' =>	'clemencia'],
		['deparment_id' => 13, 'cod' => 244, 'name' =>	'el carmen de bolivar'],
		['deparment_id' => 13, 'cod' => 248, 'name' =>	'el guamo'],
		['deparment_id' => 13, 'cod' => 268, 'name' =>	'el peñon'],
		['deparment_id' => 13, 'cod' => 300, 'name' =>	'hatillo de loba'],
		['deparment_id' => 13, 'cod' => 430, 'name' =>	'magangue'],
		['deparment_id' => 13, 'cod' => 433, 'name' =>	'mahates'],
		['deparment_id' => 13, 'cod' => 440, 'name' =>	'margarita'],
		['deparment_id' => 13, 'cod' => 442, 'name' =>	'maria la baja'],
		['deparment_id' => 13, 'cod' => 458, 'name' =>	'montecristo'],
		['deparment_id' => 13, 'cod' => 468, 'name' =>	'mompos'],
		['deparment_id' => 13, 'cod' => 490, 'name' =>	'norosi'],
		['deparment_id' => 13, 'cod' => 473, 'name' =>	'morales'],
		['deparment_id' => 13, 'cod' => 549, 'name' =>	'pinillos'],
		['deparment_id' => 13, 'cod' => 580, 'name' =>	'regidor'],
		['deparment_id' => 13, 'cod' => 600, 'name' =>	'rio viejo'],
		['deparment_id' => 13, 'cod' => 620, 'name' =>	'san cristobal'],
		['deparment_id' => 13, 'cod' => 647, 'name' =>	'san estanislao'],
		['deparment_id' => 13, 'cod' => 650, 'name' =>	'san fernando'],
		['deparment_id' => 13, 'cod' => 654, 'name' =>	'san jacinto'],
		['deparment_id' => 13, 'cod' => 655, 'name' =>	'san jacinto del cauca'],
		['deparment_id' => 13, 'cod' => 657, 'name' =>	'san juan nepomuceno'],
		['deparment_id' => 13, 'cod' => 667, 'name' =>	'san martin de loba'],
		['deparment_id' => 13, 'cod' => 670, 'name' =>	'san pablo'],
		['deparment_id' => 13, 'cod' => 673, 'name' =>	'santa catalina'],
		['deparment_id' => 13, 'cod' => 683, 'name' =>	'santa rosa'],
		['deparment_id' => 13, 'cod' => 688, 'name' =>	'santa rosa del sur'],
		['deparment_id' => 13, 'cod' => 744, 'name' =>	'simiti'],
		['deparment_id' => 13, 'cod' => 760, 'name' =>	'soplaviento'],
		['deparment_id' => 13, 'cod' => 780, 'name' =>	'talaigua nuevo'],
		['deparment_id' => 13, 'cod' => 810, 'name' =>	'tiquisio'],
		['deparment_id' => 13, 'cod' => 836, 'name' =>	'turbaco'],
		['deparment_id' => 13, 'cod' => 838, 'name' =>	'turbana'],
		['deparment_id' => 13, 'cod' => 873, 'name' =>	'villanueva'],
		['deparment_id' => 13, 'cod' => 894, 'name' =>	'zambrano'],
		['deparment_id' => 15, 'cod' => 1, 'name' =>	'tunja'],
		['deparment_id' => 15, 'cod' => 22, 'name' =>	'almeida'],
		['deparment_id' => 15, 'cod' => 47, 'name' =>	'aquitania'],
		['deparment_id' => 15, 'cod' => 51, 'name' =>	'arcabuco'],
		['deparment_id' => 15, 'cod' => 87, 'name' =>	'belen'],
		['deparment_id' => 15, 'cod' => 90, 'name' =>	'berbeo'],
		['deparment_id' => 15, 'cod' => 92, 'name' =>	'beteitiva'],
		['deparment_id' => 15, 'cod' => 97, 'name' =>	'boavita'],
		['deparment_id' => 15, 'cod' => 104, 'name' =>	'boyaca'],
		['deparment_id' => 15, 'cod' => 106, 'name' =>	'briceño'],
		['deparment_id' => 15, 'cod' => 109, 'name' =>	'buenavista'],
		['deparment_id' => 15, 'cod' => 114, 'name' =>	'busbanza'],
		['deparment_id' => 15, 'cod' => 131, 'name' =>	'caldas'],
		['deparment_id' => 15, 'cod' => 135, 'name' =>	'campohermoso'],
		['deparment_id' => 15, 'cod' => 162, 'name' =>	'cerinza'],
		['deparment_id' => 15, 'cod' => 172, 'name' =>	'chinavita'],
		['deparment_id' => 15, 'cod' => 176, 'name' =>	'chiquinquira'],
		['deparment_id' => 15, 'cod' => 180, 'name' =>	'chiscas'],
		['deparment_id' => 15, 'cod' => 183, 'name' =>	'chita'],
		['deparment_id' => 15, 'cod' => 185, 'name' =>	'chitaraque'],
		['deparment_id' => 15, 'cod' => 187, 'name' =>	'chivata'],
		['deparment_id' => 15, 'cod' => 189, 'name' =>	'cienega'],
		['deparment_id' => 15, 'cod' => 204, 'name' =>	'combita'],
		['deparment_id' => 15, 'cod' => 212, 'name' =>	'coper'],
		['deparment_id' => 15, 'cod' => 215, 'name' =>	'corrales'],
		['deparment_id' => 15, 'cod' => 218, 'name' =>	'covarachia'],
		['deparment_id' => 15, 'cod' => 223, 'name' =>	'cubara'],
		['deparment_id' => 15, 'cod' => 224, 'name' =>	'cucaita'],
		['deparment_id' => 15, 'cod' => 226, 'name' =>	'cuitiva'],
		['deparment_id' => 15, 'cod' => 232, 'name' =>	'chiquiza'],
		['deparment_id' => 15, 'cod' => 236, 'name' =>	'chivor'],
		['deparment_id' => 15, 'cod' => 238, 'name' =>	'duitama'],
		['deparment_id' => 15, 'cod' => 244, 'name' =>	'el cocuy'],
		['deparment_id' => 15, 'cod' => 248, 'name' =>	'el espino'],
		['deparment_id' => 15, 'cod' => 272, 'name' =>	'firavitoba'],
		['deparment_id' => 15, 'cod' => 276, 'name' =>	'floresta'],
		['deparment_id' => 15, 'cod' => 293, 'name' =>	'gachantiva'],
		['deparment_id' => 15, 'cod' => 296, 'name' =>	'gameza'],
		['deparment_id' => 15, 'cod' => 299, 'name' =>	'garagoa'],
		['deparment_id' => 15, 'cod' => 317, 'name' =>	'guacamayas'],
		['deparment_id' => 15, 'cod' => 322, 'name' =>	'guateque'],
		['deparment_id' => 15, 'cod' => 325, 'name' =>	'guayata'],
		['deparment_id' => 15, 'cod' => 332, 'name' =>	'gsican'],
		['deparment_id' => 15, 'cod' => 362, 'name' =>	'iza'],
		['deparment_id' => 15, 'cod' => 367, 'name' =>	'jenesano'],
		['deparment_id' => 15, 'cod' => 368, 'name' =>	'jerico'],
		['deparment_id' => 15, 'cod' => 377, 'name' =>	'labranzagrande'],
		['deparment_id' => 15, 'cod' => 380, 'name' =>	'la capilla'],
		['deparment_id' => 15, 'cod' => 401, 'name' =>	'la victoria'],
		['deparment_id' => 15, 'cod' => 403, 'name' =>	'la uvita'],
		['deparment_id' => 15, 'cod' => 407, 'name' =>	'villa de leyva'],
		['deparment_id' => 15, 'cod' => 425, 'name' =>	'macanal'],
		['deparment_id' => 15, 'cod' => 442, 'name' =>	'maripi'],
		['deparment_id' => 15, 'cod' => 455, 'name' =>	'miraflores'],
		['deparment_id' => 15, 'cod' => 464, 'name' =>	'mongua'],
		['deparment_id' => 15, 'cod' => 466, 'name' =>	'mongui'],
		['deparment_id' => 15, 'cod' => 469, 'name' =>	'moniquira'],
		['deparment_id' => 15, 'cod' => 476, 'name' =>	'motavita'],
		['deparment_id' => 15, 'cod' => 480, 'name' =>	'muzo'],
		['deparment_id' => 15, 'cod' => 491, 'name' =>	'nobsa'],
		['deparment_id' => 15, 'cod' => 494, 'name' =>	'nuevo colon'],
		['deparment_id' => 15, 'cod' => 500, 'name' =>	'oicata'],
		['deparment_id' => 15, 'cod' => 507, 'name' =>	'otanche'],
		['deparment_id' => 15, 'cod' => 511, 'name' =>	'pachavita'],
		['deparment_id' => 15, 'cod' => 514, 'name' =>	'paez'],
		['deparment_id' => 15, 'cod' => 516, 'name' =>	'paipa'],
		['deparment_id' => 15, 'cod' => 518, 'name' =>	'pajarito'],
		['deparment_id' => 15, 'cod' => 522, 'name' =>	'panqueba'],
		['deparment_id' => 15, 'cod' => 531, 'name' =>	'pauna'],
		['deparment_id' => 15, 'cod' => 533, 'name' =>	'paya'],
		['deparment_id' => 15, 'cod' => 537, 'name' =>	'paz de rio'],
		['deparment_id' => 15, 'cod' => 542, 'name' =>	'pesca'],
		['deparment_id' => 15, 'cod' => 550, 'name' =>	'pisba'],
		['deparment_id' => 15, 'cod' => 572, 'name' =>	'puerto boyaca'],
		['deparment_id' => 15, 'cod' => 580, 'name' =>	'quipama'],
		['deparment_id' => 15, 'cod' => 599, 'name' =>	'ramiriqui'],
		['deparment_id' => 15, 'cod' => 600, 'name' =>	'raquira'],
		['deparment_id' => 15, 'cod' => 621, 'name' =>	'rondon'],
		['deparment_id' => 15, 'cod' => 632, 'name' =>	'saboya'],
		['deparment_id' => 15, 'cod' => 638, 'name' =>	'sachica'],
		['deparment_id' => 15, 'cod' => 646, 'name' =>	'samaca'],
		['deparment_id' => 15, 'cod' => 660, 'name' =>	'san eduardo'],
		['deparment_id' => 15, 'cod' => 664, 'name' =>	'san jose de pare'],
		['deparment_id' => 15, 'cod' => 667, 'name' =>	'san luis de gaceno'],
		['deparment_id' => 15, 'cod' => 673, 'name' =>	'san mateo'],
		['deparment_id' => 15, 'cod' => 676, 'name' =>	'san miguel de sema'],
		['deparment_id' => 15, 'cod' => 681, 'name' =>	'san pablo de borbur'],
		['deparment_id' => 15, 'cod' => 686, 'name' =>	'santana'],
		['deparment_id' => 15, 'cod' => 690, 'name' =>	'santa maria'],
		['deparment_id' => 15, 'cod' => 693, 'name' =>	'santa rosa de viterbo'],
		['deparment_id' => 15, 'cod' => 696, 'name' =>	'santa sofia'],
		['deparment_id' => 15, 'cod' => 720, 'name' =>	'sativanorte'],
		['deparment_id' => 15, 'cod' => 723, 'name' =>	'sativasur'],
		['deparment_id' => 15, 'cod' => 740, 'name' =>	'siachoque'],
		['deparment_id' => 15, 'cod' => 753, 'name' =>	'soata'],
		['deparment_id' => 15, 'cod' => 755, 'name' =>	'socota'],
		['deparment_id' => 15, 'cod' => 757, 'name' =>	'socha'],
		['deparment_id' => 15, 'cod' => 759, 'name' =>	'sogamoso'],
		['deparment_id' => 15, 'cod' => 761, 'name' =>	'somondoco'],
		['deparment_id' => 15, 'cod' => 762, 'name' =>	'sora'],
		['deparment_id' => 15, 'cod' => 763, 'name' =>	'sotaquira'],
		['deparment_id' => 15, 'cod' => 764, 'name' =>	'soraca'],
		['deparment_id' => 15, 'cod' => 774, 'name' =>	'susacon'],
		['deparment_id' => 15, 'cod' => 776, 'name' =>	'sutamarchan'],
		['deparment_id' => 15, 'cod' => 778, 'name' =>	'sutatenza'],
		['deparment_id' => 15, 'cod' => 790, 'name' =>	'tasco'],
		['deparment_id' => 15, 'cod' => 798, 'name' =>	'tenza'],
		['deparment_id' => 15, 'cod' => 804, 'name' =>	'tibana'],
		['deparment_id' => 15, 'cod' => 806, 'name' =>	'tibasosa'],
		['deparment_id' => 15, 'cod' => 808, 'name' =>	'tinjaca'],
		['deparment_id' => 15, 'cod' => 810, 'name' =>	'tipacoque'],
		['deparment_id' => 15, 'cod' => 814, 'name' =>	'toca'],
		['deparment_id' => 15, 'cod' => 816, 'name' =>	'togsi'],
		['deparment_id' => 15, 'cod' => 820, 'name' =>	'topaga'],
		['deparment_id' => 15, 'cod' => 822, 'name' =>	'tota'],
		['deparment_id' => 15, 'cod' => 832, 'name' =>	'tunungua'],
		['deparment_id' => 15, 'cod' => 835, 'name' =>	'turmeque'],
		['deparment_id' => 15, 'cod' => 837, 'name' =>	'tuta'],
		['deparment_id' => 15, 'cod' => 839, 'name' =>	'tutaza'],
		['deparment_id' => 15, 'cod' => 842, 'name' =>	'umbita'],
		['deparment_id' => 15, 'cod' => 861, 'name' =>	'ventaquemada'],
		['deparment_id' => 15, 'cod' => 879, 'name' =>	'viracacha'],
		['deparment_id' => 15, 'cod' => 897, 'name' =>	'zetaquira'],
		['deparment_id' => 17, 'cod' => 1, 'name' =>	'manizales'],
		['deparment_id' => 17, 'cod' => 13, 'name' =>	'aguadas'],
		['deparment_id' => 17, 'cod' => 42, 'name' =>	'anserma'],
		['deparment_id' => 17, 'cod' => 50, 'name' =>	'aranzazu'],
		['deparment_id' => 17, 'cod' => 88, 'name' =>	'belalcazar'],
		['deparment_id' => 17, 'cod' => 174, 'name' =>	'chinchina'],
		['deparment_id' => 17, 'cod' => 272, 'name' =>	'filadelfia'],
		['deparment_id' => 17, 'cod' => 380, 'name' =>	'la dorada'],
		['deparment_id' => 17, 'cod' => 388, 'name' =>	'la merced'],
		['deparment_id' => 17, 'cod' => 433, 'name' =>	'manzanares'],
		['deparment_id' => 17, 'cod' => 442, 'name' =>	'marmato'],
		['deparment_id' => 17, 'cod' => 444, 'name' =>	'marquetalia'],
		['deparment_id' => 17, 'cod' => 446, 'name' =>	'marulanda'],
		['deparment_id' => 17, 'cod' => 486, 'name' =>	'neira'],
		['deparment_id' => 17, 'cod' => 495, 'name' =>	'norcasia'],
		['deparment_id' => 17, 'cod' => 513, 'name' =>	'pacora'],
		['deparment_id' => 17, 'cod' => 524, 'name' =>	'palestina'],
		['deparment_id' => 17, 'cod' => 541, 'name' =>	'pensilvania'],
		['deparment_id' => 17, 'cod' => 614, 'name' =>	'riosucio'],
		['deparment_id' => 17, 'cod' => 616, 'name' =>	'risaralda'],
		['deparment_id' => 17, 'cod' => 653, 'name' =>	'salamina'],
		['deparment_id' => 17, 'cod' => 662, 'name' =>	'samana'],
		['deparment_id' => 17, 'cod' => 665, 'name' =>	'san jose'],
		['deparment_id' => 17, 'cod' => 777, 'name' =>	'supia'],
		['deparment_id' => 17, 'cod' => 867, 'name' =>	'victoria'],
		['deparment_id' => 17, 'cod' => 873, 'name' =>	'villamaria'],
		['deparment_id' => 17, 'cod' => 877, 'name' =>	'viterbo'],
		['deparment_id' => 18, 'cod' => 1, 'name' =>	'florencia'],
		['deparment_id' => 18, 'cod' => 29, 'name' =>	'albania'],
		['deparment_id' => 18, 'cod' => 94, 'name' =>	'belen de los andaquies'],
		['deparment_id' => 18, 'cod' => 150, 'name' =>	'cartagena del chaira'],
		['deparment_id' => 18, 'cod' => 205, 'name' =>	'curillo'],
		['deparment_id' => 18, 'cod' => 247, 'name' =>	'el doncello'],
		['deparment_id' => 18, 'cod' => 256, 'name' =>	'el paujil'],
		['deparment_id' => 18, 'cod' => 410, 'name' =>	'la montañita'],
		['deparment_id' => 18, 'cod' => 460, 'name' =>	'milan'],
		['deparment_id' => 18, 'cod' => 479, 'name' =>	'morelia'],
		['deparment_id' => 18, 'cod' => 592, 'name' =>	'puerto rico'],
		['deparment_id' => 18, 'cod' => 610, 'name' =>	'san jose del fragua'],
		['deparment_id' => 18, 'cod' => 753, 'name' =>	'san vicente del caguan'],
		['deparment_id' => 18, 'cod' => 756, 'name' =>	'solano'],
		['deparment_id' => 18, 'cod' => 785, 'name' =>	'solita'],
		['deparment_id' => 18, 'cod' => 860, 'name' =>	'valparaiso'],
		['deparment_id' => 19, 'cod' => 1, 'name' =>	'popayan'],
		['deparment_id' => 19, 'cod' => 22, 'name' =>	'almaguer'],
		['deparment_id' => 19, 'cod' => 50, 'name' =>	'argelia'],
		['deparment_id' => 19, 'cod' => 75, 'name' =>	'balboa'],
		['deparment_id' => 19, 'cod' => 100, 'name' =>	'bolivar'],
		['deparment_id' => 19, 'cod' => 110, 'name' =>	'buenos aires'],
		['deparment_id' => 19, 'cod' => 130, 'name' =>	'cajibio'],
		['deparment_id' => 19, 'cod' => 137, 'name' =>	'caldono'],
		['deparment_id' => 19, 'cod' => 142, 'name' =>	'caloto'],
		['deparment_id' => 19, 'cod' => 212, 'name' =>	'corinto'],
		['deparment_id' => 19, 'cod' => 256, 'name' =>	'el tambo'],
		['deparment_id' => 19, 'cod' => 290, 'name' =>	'florencia'],
		['deparment_id' => 19, 'cod' => 300, 'name' =>	'guachene'],
		['deparment_id' => 19, 'cod' => 318, 'name' =>	'guapi'],
		['deparment_id' => 19, 'cod' => 355, 'name' =>	'inza'],
		['deparment_id' => 19, 'cod' => 364, 'name' =>	'jambalo'],
		['deparment_id' => 19, 'cod' => 392, 'name' =>	'la sierra'],
		['deparment_id' => 19, 'cod' => 397, 'name' =>	'la vega'],
		['deparment_id' => 19, 'cod' => 418, 'name' =>	'lopez'],
		['deparment_id' => 19, 'cod' => 450, 'name' =>	'mercaderes'],
		['deparment_id' => 19, 'cod' => 455, 'name' =>	'miranda'],
		['deparment_id' => 19, 'cod' => 473, 'name' =>	'morales'],
		['deparment_id' => 19, 'cod' => 513, 'name' =>	'padilla'],
		['deparment_id' => 19, 'cod' => 517, 'name' =>	'paez'],
		['deparment_id' => 19, 'cod' => 532, 'name' =>	'patia'],
		['deparment_id' => 19, 'cod' => 533, 'name' =>	'piamonte'],
		['deparment_id' => 19, 'cod' => 548, 'name' =>	'piendamo'],
		['deparment_id' => 19, 'cod' => 573, 'name' =>	'puerto tejada'],
		['deparment_id' => 19, 'cod' => 585, 'name' =>	'purace'],
		['deparment_id' => 19, 'cod' => 622, 'name' =>	'rosas'],
		['deparment_id' => 19, 'cod' => 693, 'name' =>	'san sebastian'],
		['deparment_id' => 19, 'cod' => 698, 'name' =>	'santander de quilichao'],
		['deparment_id' => 19, 'cod' => 701, 'name' =>	'santa rosa'],
		['deparment_id' => 19, 'cod' => 743, 'name' =>	'silvia'],
		['deparment_id' => 19, 'cod' => 760, 'name' =>	'sotara'],
		['deparment_id' => 19, 'cod' => 780, 'name' =>	'suarez'],
		['deparment_id' => 19, 'cod' => 785, 'name' =>	'sucre'],
		['deparment_id' => 19, 'cod' => 807, 'name' =>	'timbio'],
		['deparment_id' => 19, 'cod' => 809, 'name' =>	'timbiqui'],
		['deparment_id' => 19, 'cod' => 821, 'name' =>	'toribio'],
		['deparment_id' => 19, 'cod' => 824, 'name' =>	'totoro'],
		['deparment_id' => 19, 'cod' => 845, 'name' =>	'villa rica'],
		['deparment_id' => 20, 'cod' => 1, 'name' =>	'valledupar'],
		['deparment_id' => 20, 'cod' => 11, 'name' =>	'aguachica'],
		['deparment_id' => 20, 'cod' => 13, 'name' =>	'agustin codazzi'],
		['deparment_id' => 20, 'cod' => 32, 'name' =>	'astrea'],
		['deparment_id' => 20, 'cod' => 45, 'name' =>	'becerril'],
		['deparment_id' => 20, 'cod' => 60, 'name' =>	'bosconia'],
		['deparment_id' => 20, 'cod' => 175, 'name' =>	'chimichagua'],
		['deparment_id' => 20, 'cod' => 178, 'name' =>	'chiriguana'],
		['deparment_id' => 20, 'cod' => 228, 'name' =>	'curumani'],
		['deparment_id' => 20, 'cod' => 238, 'name' =>	'el copey'],
		['deparment_id' => 20, 'cod' => 250, 'name' =>	'el paso'],
		['deparment_id' => 20, 'cod' => 295, 'name' =>	'gamarra'],
		['deparment_id' => 20, 'cod' => 310, 'name' =>	'gonzalez'],
		['deparment_id' => 20, 'cod' => 383, 'name' =>	'la gloria'],
		['deparment_id' => 20, 'cod' => 400, 'name' =>	'la jagua de ibirico'],
		['deparment_id' => 20, 'cod' => 443, 'name' =>	'manaure'],
		['deparment_id' => 20, 'cod' => 517, 'name' =>	'pailitas'],
		['deparment_id' => 20, 'cod' => 550, 'name' =>	'pelaya'],
		['deparment_id' => 20, 'cod' => 570, 'name' =>	'pueblo bello'],
		['deparment_id' => 20, 'cod' => 614, 'name' =>	'rio de oro'],
		['deparment_id' => 20, 'cod' => 621, 'name' =>	'la paz'],
		['deparment_id' => 20, 'cod' => 710, 'name' =>	'san alberto'],
		['deparment_id' => 20, 'cod' => 750, 'name' =>	'san diego'],
		['deparment_id' => 20, 'cod' => 770, 'name' =>	'san martin'],
		['deparment_id' => 20, 'cod' => 787, 'name' =>	'tamalameque'],
		['deparment_id' => 23, 'cod' => 1, 'name' =>	'monteria'],
		['deparment_id' => 23, 'cod' => 68, 'name' =>	'ayapel'],
		['deparment_id' => 23, 'cod' => 79, 'name' =>	'buenavista'],
		['deparment_id' => 23, 'cod' => 90, 'name' =>	'canalete'],
		['deparment_id' => 23, 'cod' => 162, 'name' =>	'cerete'],
		['deparment_id' => 23, 'cod' => 168, 'name' =>	'chima'],
		['deparment_id' => 23, 'cod' => 182, 'name' =>	'chinu'],
		['deparment_id' => 23, 'cod' => 189, 'name' =>	'cienaga de oro'],
		['deparment_id' => 23, 'cod' => 300, 'name' =>	'cotorra'],
		['deparment_id' => 23, 'cod' => 350, 'name' =>	'la apartada'],
		['deparment_id' => 23, 'cod' => 417, 'name' =>	'lorica'],
		['deparment_id' => 23, 'cod' => 419, 'name' =>	'los cordobas'],
		['deparment_id' => 23, 'cod' => 464, 'name' =>	'momil'],
		['deparment_id' => 23, 'cod' => 466, 'name' =>	'montelibano'],
		['deparment_id' => 23, 'cod' => 500, 'name' =>	'moñitos'],
		['deparment_id' => 23, 'cod' => 555, 'name' =>	'planeta rica'],
		['deparment_id' => 23, 'cod' => 570, 'name' =>	'pueblo nuevo'],
		['deparment_id' => 23, 'cod' => 574, 'name' =>	'puerto escondido'],
		['deparment_id' => 23, 'cod' => 580, 'name' =>	'puerto libertador'],
		['deparment_id' => 23, 'cod' => 586, 'name' =>	'purisima'],
		['deparment_id' => 23, 'cod' => 660, 'name' =>	'sahagun'],
		['deparment_id' => 23, 'cod' => 670, 'name' =>	'san andres sotavento'],
		['deparment_id' => 23, 'cod' => 672, 'name' =>	'san antero'],
		['deparment_id' => 23, 'cod' => 675, 'name' =>	'san bernardo del viento'],
		['deparment_id' => 23, 'cod' => 678, 'name' =>	'san carlos'],
		['deparment_id' => 23, 'cod' => 686, 'name' =>	'san pelayo'],
		['deparment_id' => 23, 'cod' => 807, 'name' =>	'tierralta'],
		['deparment_id' => 23, 'cod' => 855, 'name' =>	'valencia'],
		['deparment_id' => 25, 'cod' => 1, 'name' =>	'agua de dios'],
		['deparment_id' => 25, 'cod' => 19, 'name' =>	'alban'],
		['deparment_id' => 25, 'cod' => 35, 'name' =>	'anapoima'],
		['deparment_id' => 25, 'cod' => 40, 'name' =>	'anolaima'],
		['deparment_id' => 25, 'cod' => 53, 'name' =>	'arbelaez'],
		['deparment_id' => 25, 'cod' => 86, 'name' =>	'beltran'],
		['deparment_id' => 25, 'cod' => 95, 'name' =>	'bituima'],
		['deparment_id' => 25, 'cod' => 99, 'name' =>	'bojaca'],
		['deparment_id' => 25, 'cod' => 120, 'name' =>	'cabrera'],
		['deparment_id' => 25, 'cod' => 123, 'name' =>	'cachipay'],
		['deparment_id' => 25, 'cod' => 126, 'name' =>	'cajica'],
		['deparment_id' => 25, 'cod' => 148, 'name' =>	'caparrapi'],
		['deparment_id' => 25, 'cod' => 151, 'name' =>	'caqueza'],
		['deparment_id' => 25, 'cod' => 154, 'name' =>	'carmen de carupa'],
		['deparment_id' => 25, 'cod' => 168, 'name' =>	'chaguani'],
		['deparment_id' => 25, 'cod' => 175, 'name' =>	'chia'],
		['deparment_id' => 25, 'cod' => 178, 'name' =>	'chipaque'],
		['deparment_id' => 25, 'cod' => 181, 'name' =>	'choachi'],
		['deparment_id' => 25, 'cod' => 183, 'name' =>	'choconta'],
		['deparment_id' => 25, 'cod' => 200, 'name' =>	'cogua'],
		['deparment_id' => 25, 'cod' => 214, 'name' =>	'cota'],
		['deparment_id' => 25, 'cod' => 224, 'name' =>	'cucunuba'],
		['deparment_id' => 25, 'cod' => 245, 'name' =>	'el colegio'],
		['deparment_id' => 25, 'cod' => 258, 'name' =>	'el peñon'],
		['deparment_id' => 25, 'cod' => 260, 'name' =>	'el rosal'],
		['deparment_id' => 25, 'cod' => 269, 'name' =>	'facatativa'],
		['deparment_id' => 25, 'cod' => 279, 'name' =>	'fomeque'],
		['deparment_id' => 25, 'cod' => 281, 'name' =>	'fosca'],
		['deparment_id' => 25, 'cod' => 286, 'name' =>	'funza'],
		['deparment_id' => 25, 'cod' => 288, 'name' =>	'fuquene'],
		['deparment_id' => 25, 'cod' => 290, 'name' =>	'fusagasuga'],
		['deparment_id' => 25, 'cod' => 293, 'name' =>	'gachala'],
		['deparment_id' => 25, 'cod' => 295, 'name' =>	'gachancipa'],
		['deparment_id' => 25, 'cod' => 297, 'name' =>	'gacheta'],
		['deparment_id' => 25, 'cod' => 299, 'name' =>	'gama'],
		['deparment_id' => 25, 'cod' => 307, 'name' =>	'girardot'],
		['deparment_id' => 25, 'cod' => 312, 'name' =>	'granada'],
		['deparment_id' => 25, 'cod' => 317, 'name' =>	'guacheta'],
		['deparment_id' => 25, 'cod' => 320, 'name' =>	'guaduas'],
		['deparment_id' => 25, 'cod' => 322, 'name' =>	'guasca'],
		['deparment_id' => 25, 'cod' => 324, 'name' =>	'guataqui'],
		['deparment_id' => 25, 'cod' => 326, 'name' =>	'guatavita'],
		['deparment_id' => 25, 'cod' => 328, 'name' =>	'guayabal de siquima'],
		['deparment_id' => 25, 'cod' => 335, 'name' =>	'guayabetal'],
		['deparment_id' => 25, 'cod' => 339, 'name' =>	'gutierrez'],
		['deparment_id' => 25, 'cod' => 368, 'name' =>	'jerusalen'],
		['deparment_id' => 25, 'cod' => 372, 'name' =>	'junin'],
		['deparment_id' => 25, 'cod' => 377, 'name' =>	'la calera'],
		['deparment_id' => 25, 'cod' => 386, 'name' =>	'la mesa'],
		['deparment_id' => 25, 'cod' => 394, 'name' =>	'la palma'],
		['deparment_id' => 25, 'cod' => 398, 'name' =>	'la peña'],
		['deparment_id' => 25, 'cod' => 402, 'name' =>	'la vega'],
		['deparment_id' => 25, 'cod' => 407, 'name' =>	'lenguazaque'],
		['deparment_id' => 25, 'cod' => 426, 'name' =>	'macheta'],
		['deparment_id' => 25, 'cod' => 430, 'name' =>	'madrid'],
		['deparment_id' => 25, 'cod' => 436, 'name' =>	'manta'],
		['deparment_id' => 25, 'cod' => 438, 'name' =>	'medina'],
		['deparment_id' => 25, 'cod' => 473, 'name' =>	'mosquera'],
		['deparment_id' => 25, 'cod' => 483, 'name' =>	'nariño'],
		['deparment_id' => 25, 'cod' => 486, 'name' =>	'nemocon'],
		['deparment_id' => 25, 'cod' => 488, 'name' =>	'nilo'],
		['deparment_id' => 25, 'cod' => 489, 'name' =>	'nimaima'],
		['deparment_id' => 25, 'cod' => 491, 'name' =>	'nocaima'],
		['deparment_id' => 25, 'cod' => 506, 'name' =>	'venecia'],
		['deparment_id' => 25, 'cod' => 513, 'name' =>	'pacho'],
		['deparment_id' => 25, 'cod' => 518, 'name' =>	'paime'],
		['deparment_id' => 25, 'cod' => 524, 'name' =>	'pandi'],
		['deparment_id' => 25, 'cod' => 530, 'name' =>	'paratebueno'],
		['deparment_id' => 25, 'cod' => 535, 'name' =>	'pasca'],
		['deparment_id' => 25, 'cod' => 572, 'name' =>	'puerto salgar'],
		['deparment_id' => 25, 'cod' => 580, 'name' =>	'puli'],
		['deparment_id' => 25, 'cod' => 592, 'name' =>	'quebradanegra'],
		['deparment_id' => 25, 'cod' => 594, 'name' =>	'quetame'],
		['deparment_id' => 25, 'cod' => 596, 'name' =>	'quipile'],
		['deparment_id' => 25, 'cod' => 599, 'name' =>	'apulo'],
		['deparment_id' => 25, 'cod' => 612, 'name' =>	'ricaurte'],
		['deparment_id' => 25, 'cod' => 645, 'name' =>	'san antonio del tequendama'],
		['deparment_id' => 25, 'cod' => 649, 'name' =>	'san bernardo'],
		['deparment_id' => 25, 'cod' => 653, 'name' =>	'san cayetano'],
		['deparment_id' => 25, 'cod' => 658, 'name' =>	'san francisco'],
		['deparment_id' => 25, 'cod' => 662, 'name' =>	'san juan de rio seco'],
		['deparment_id' => 25, 'cod' => 718, 'name' =>	'sasaima'],
		['deparment_id' => 25, 'cod' => 736, 'name' =>	'sesquile'],
		['deparment_id' => 25, 'cod' => 740, 'name' =>	'sibate'],
		['deparment_id' => 25, 'cod' => 743, 'name' =>	'silvania'],
		['deparment_id' => 25, 'cod' => 745, 'name' =>	'simijaca'],
		['deparment_id' => 25, 'cod' => 754, 'name' =>	'soacha'],
		['deparment_id' => 25, 'cod' => 758, 'name' =>	'sopo'],
		['deparment_id' => 25, 'cod' => 769, 'name' =>	'subachoque'],
		['deparment_id' => 25, 'cod' => 772, 'name' =>	'suesca'],
		['deparment_id' => 25, 'cod' => 777, 'name' =>	'supata'],
		['deparment_id' => 25, 'cod' => 779, 'name' =>	'susa'],
		['deparment_id' => 25, 'cod' => 781, 'name' =>	'sutatausa'],
		['deparment_id' => 25, 'cod' => 785, 'name' =>	'tabio'],
		['deparment_id' => 25, 'cod' => 793, 'name' =>	'tausa'],
		['deparment_id' => 25, 'cod' => 797, 'name' =>	'tena'],
		['deparment_id' => 25, 'cod' => 799, 'name' =>	'tenjo'],
		['deparment_id' => 25, 'cod' => 805, 'name' =>	'tibacuy'],
		['deparment_id' => 25, 'cod' => 807, 'name' =>	'tibirita'],
		['deparment_id' => 25, 'cod' => 815, 'name' =>	'tocaima'],
		['deparment_id' => 25, 'cod' => 817, 'name' =>	'tocancipa'],
		['deparment_id' => 25, 'cod' => 823, 'name' =>	'topaipi'],
		['deparment_id' => 25, 'cod' => 839, 'name' =>	'ubala'],
		['deparment_id' => 25, 'cod' => 841, 'name' =>	'ubaque'],
		['deparment_id' => 25, 'cod' => 843, 'name' =>	'villa de san diego de ubate'],
		['deparment_id' => 25, 'cod' => 845, 'name' =>	'une'],
		['deparment_id' => 25, 'cod' => 851, 'name' =>	'utica'],
		['deparment_id' => 25, 'cod' => 862, 'name' =>	'vergara'],
		['deparment_id' => 25, 'cod' => 867, 'name' =>	'viani'],
		['deparment_id' => 25, 'cod' => 871, 'name' =>	'villagomez'],
		['deparment_id' => 25, 'cod' => 873, 'name' =>	'villapinzon'],
		['deparment_id' => 25, 'cod' => 875, 'name' =>	'villeta'],
		['deparment_id' => 25, 'cod' => 878, 'name' =>	'viota'],
		['deparment_id' => 25, 'cod' => 885, 'name' =>	'yacopi'],
		['deparment_id' => 25, 'cod' => 898, 'name' =>	'zipacon'],
		['deparment_id' => 25, 'cod' => 899, 'name' =>	'zipaquira'],
		['deparment_id' => 27, 'cod' => 1, 'name' =>	'quibdo'],
		['deparment_id' => 27, 'cod' => 6, 'name' =>	'acandi'],
		['deparment_id' => 27, 'cod' => 25, 'name' =>	'alto baudo'],
		['deparment_id' => 27, 'cod' => 50, 'name' =>	'atrato'],
		['deparment_id' => 27, 'cod' => 73, 'name' =>	'bagado'],
		['deparment_id' => 27, 'cod' => 75, 'name' =>	'bahia solano'],
		['deparment_id' => 27, 'cod' => 77, 'name' =>	'bajo baudo'],
		['deparment_id' => 27, 'cod' => 99, 'name' =>	'bojaya'],
		['deparment_id' => 27, 'cod' => 135, 'name' =>	'el canton del san pablo'],
		['deparment_id' => 27, 'cod' => 150, 'name' =>	'carmen del darien'],
		['deparment_id' => 27, 'cod' => 160, 'name' =>	'certegui'],
		['deparment_id' => 27, 'cod' => 205, 'name' =>	'condoto'],
		['deparment_id' => 27, 'cod' => 245, 'name' =>	'el carmen de atrato'],
		['deparment_id' => 27, 'cod' => 250, 'name' =>	'el litoral del san juan'],
		['deparment_id' => 27, 'cod' => 361, 'name' =>	'istmina'],
		['deparment_id' => 27, 'cod' => 372, 'name' =>	'jurado'],
		['deparment_id' => 27, 'cod' => 413, 'name' =>	'lloro'],
		['deparment_id' => 27, 'cod' => 425, 'name' =>	'medio atrato'],
		['deparment_id' => 27, 'cod' => 430, 'name' =>	'medio baudo'],
		['deparment_id' => 27, 'cod' => 450, 'name' =>	'medio san juan'],
		['deparment_id' => 27, 'cod' => 491, 'name' =>	'novita'],
		['deparment_id' => 27, 'cod' => 495, 'name' =>	'nuqui'],
		['deparment_id' => 27, 'cod' => 580, 'name' =>	'rio iro'],
		['deparment_id' => 27, 'cod' => 600, 'name' =>	'rio quito'],
		['deparment_id' => 27, 'cod' => 615, 'name' =>	'riosucio'],
		['deparment_id' => 27, 'cod' => 660, 'name' =>	'san jose del palmar'],
		['deparment_id' => 27, 'cod' => 745, 'name' =>	'sipi'],
		['deparment_id' => 27, 'cod' => 787, 'name' =>	'tado'],
		['deparment_id' => 27, 'cod' => 800, 'name' =>	'unguia'],
		['deparment_id' => 27, 'cod' => 810, 'name' =>	'union panamericana'],
		['deparment_id' => 41, 'cod' => 1, 'name' =>	'neiva'],
		['deparment_id' => 41, 'cod' => 6, 'name' =>	'acevedo'],
		['deparment_id' => 41, 'cod' => 13, 'name' =>	'agrado'],
		['deparment_id' => 41, 'cod' => 16, 'name' =>	'aipe'],
		['deparment_id' => 41, 'cod' => 20, 'name' =>	'algeciras'],
		['deparment_id' => 41, 'cod' => 26, 'name' =>	'altamira'],
		['deparment_id' => 41, 'cod' => 78, 'name' =>	'baraya'],
		['deparment_id' => 41, 'cod' => 132, 'name' =>	'campoalegre'],
		['deparment_id' => 41, 'cod' => 206, 'name' =>	'colombia'],
		['deparment_id' => 41, 'cod' => 244, 'name' =>	'elias'],
		['deparment_id' => 41, 'cod' => 298, 'name' =>	'garzon'],
		['deparment_id' => 41, 'cod' => 306, 'name' =>	'gigante'],
		['deparment_id' => 41, 'cod' => 319, 'name' =>	'guadalupe'],
		['deparment_id' => 41, 'cod' => 349, 'name' =>	'hobo'],
		['deparment_id' => 41, 'cod' => 357, 'name' =>	'iquira'],
		['deparment_id' => 41, 'cod' => 359, 'name' =>	'isnos'],
		['deparment_id' => 41, 'cod' => 378, 'name' =>	'la argentina'],
		['deparment_id' => 41, 'cod' => 396, 'name' =>	'la plata'],
		['deparment_id' => 41, 'cod' => 483, 'name' =>	'nataga'],
		['deparment_id' => 41, 'cod' => 503, 'name' =>	'oporapa'],
		['deparment_id' => 41, 'cod' => 518, 'name' =>	'paicol'],
		['deparment_id' => 41, 'cod' => 524, 'name' =>	'palermo'],
		['deparment_id' => 41, 'cod' => 530, 'name' =>	'palestina'],
		['deparment_id' => 41, 'cod' => 548, 'name' =>	'pital'],
		['deparment_id' => 41, 'cod' => 551, 'name' =>	'pitalito'],
		['deparment_id' => 41, 'cod' => 615, 'name' =>	'rivera'],
		['deparment_id' => 41, 'cod' => 660, 'name' =>	'saladoblanco'],
		['deparment_id' => 41, 'cod' => 668, 'name' =>	'san agustin'],
		['deparment_id' => 41, 'cod' => 676, 'name' =>	'santa maria'],
		['deparment_id' => 41, 'cod' => 770, 'name' =>	'suaza'],
		['deparment_id' => 41, 'cod' => 791, 'name' =>	'tarqui'],
		['deparment_id' => 41, 'cod' => 797, 'name' =>	'tesalia'],
		['deparment_id' => 41, 'cod' => 799, 'name' =>	'tello'],
		['deparment_id' => 41, 'cod' => 801, 'name' =>	'teruel'],
		['deparment_id' => 41, 'cod' => 807, 'name' =>	'timana'],
		['deparment_id' => 41, 'cod' => 872, 'name' =>	'villavieja'],
		['deparment_id' => 41, 'cod' => 885, 'name' =>	'yaguara'],
		['deparment_id' => 44, 'cod' => 1, 'name' =>	'riohacha'],
		['deparment_id' => 44, 'cod' => 35, 'name' =>	'albania'],
		['deparment_id' => 44, 'cod' => 78, 'name' =>	'barrancas'],
		['deparment_id' => 44, 'cod' => 90, 'name' =>	'dibulla'],
		['deparment_id' => 44, 'cod' => 98, 'name' =>	'distraccion'],
		['deparment_id' => 44, 'cod' => 110, 'name' =>	'el molino'],
		['deparment_id' => 44, 'cod' => 279, 'name' =>	'fonseca'],
		['deparment_id' => 44, 'cod' => 378, 'name' =>	'hatonuevo'],
		['deparment_id' => 44, 'cod' => 420, 'name' =>	'la jagua del pilar'],
		['deparment_id' => 44, 'cod' => 430, 'name' =>	'maicao'],
		['deparment_id' => 44, 'cod' => 560, 'name' =>	'manaure'],
		['deparment_id' => 44, 'cod' => 650, 'name' =>	'san juan del cesar'],
		['deparment_id' => 44, 'cod' => 847, 'name' =>	'uribia'],
		['deparment_id' => 44, 'cod' => 855, 'name' =>	'urumita'],
		['deparment_id' => 44, 'cod' => 874, 'name' =>	'villanueva'],
		['deparment_id' => 47, 'cod' => 1, 'name' =>	'santa marta'],
		['deparment_id' => 47, 'cod' => 30, 'name' =>	'algarrobo'],
		['deparment_id' => 47, 'cod' => 53, 'name' =>	'aracataca'],
		['deparment_id' => 47, 'cod' => 58, 'name' =>	'ariguani'],
		['deparment_id' => 47, 'cod' => 161, 'name' =>	'cerro san antonio'],
		['deparment_id' => 47, 'cod' => 170, 'name' =>	'chibolo'],
		['deparment_id' => 47, 'cod' => 189, 'name' =>	'cienaga'],
		['deparment_id' => 47, 'cod' => 205, 'name' =>	'concordia'],
		['deparment_id' => 47, 'cod' => 245, 'name' =>	'el banco'],
		['deparment_id' => 47, 'cod' => 258, 'name' =>	'el piñon'],
		['deparment_id' => 47, 'cod' => 268, 'name' =>	'el reten'],
		['deparment_id' => 47, 'cod' => 288, 'name' =>	'fundacion'],
		['deparment_id' => 47, 'cod' => 318, 'name' =>	'guamal'],
		['deparment_id' => 47, 'cod' => 460, 'name' =>	'nueva granada'],
		['deparment_id' => 47, 'cod' => 541, 'name' =>	'pedraza'],
		['deparment_id' => 47, 'cod' => 545, 'name' =>	'pijiño del carmen'],
		['deparment_id' => 47, 'cod' => 551, 'name' =>	'pivijay'],
		['deparment_id' => 47, 'cod' => 555, 'name' =>	'plato'],
		['deparment_id' => 47, 'cod' => 570, 'name' =>	'puebloviejo'],
		['deparment_id' => 47, 'cod' => 605, 'name' =>	'remolino'],
		['deparment_id' => 47, 'cod' => 660, 'name' =>	'sabanas de san angel'],
		['deparment_id' => 47, 'cod' => 675, 'name' =>	'salamina'],
		['deparment_id' => 47, 'cod' => 692, 'name' =>	'san sebastian de buenavista'],
		['deparment_id' => 47, 'cod' => 703, 'name' =>	'san zenon'],
		['deparment_id' => 47, 'cod' => 707, 'name' =>	'santa ana'],
		['deparment_id' => 47, 'cod' => 720, 'name' =>	'santa barbara de pinto'],
		['deparment_id' => 47, 'cod' => 745, 'name' =>	'sitionuevo'],
		['deparment_id' => 47, 'cod' => 798, 'name' =>	'tenerife'],
		['deparment_id' => 47, 'cod' => 960, 'name' =>	'zapayan'],
		['deparment_id' => 47, 'cod' => 980, 'name' =>	'zona bananera'],
		['deparment_id' => 50, 'cod' => 1, 'name' =>	'villavicencio', 'subregion' => 'area_metropolitana'],
		['deparment_id' => 50, 'cod' => 6, 'name' =>	'acacias', 'subregion' => 'piedemonte'],
		['deparment_id' => 50, 'cod' => 110, 'name' =>	'barranca de upia', 'subregion' => 'rio_meta'],
		['deparment_id' => 50, 'cod' => 124, 'name' =>	'cabuyaro', 'subregion' => 'rio_meta'],
		['deparment_id' => 50, 'cod' => 150, 'name' =>	'castilla la nueva', 'subregion' => 'piedemonte'],
		['deparment_id' => 50, 'cod' => 223, 'name' =>	'cubarral', 'subregion' => 'piedemonte'],
		['deparment_id' => 50, 'cod' => 226, 'name' =>	'cumaral', 'subregion' => 'area_metropolitana'],
		['deparment_id' => 50, 'cod' => 245, 'name' =>	'el calvario', 'subregion' => 'area_metropolitana'],
		['deparment_id' => 50, 'cod' => 251, 'name' =>	'el castillo', 'subregion' => 'piedemonte'],
		['deparment_id' => 50, 'cod' => 270, 'name' =>	'el dorado', 'subregion' => 'piedemonte'],
		['deparment_id' => 50, 'cod' => 287, 'name' =>	'fuente de oro', 'subregion' => 'ariari'],
		['deparment_id' => 50, 'cod' => 313, 'name' =>	'granada', 'subregion' => 'ariari'],
		['deparment_id' => 50, 'cod' => 318, 'name' =>	'guamal', 'subregion' => 'piedemonte'],
		['deparment_id' => 50, 'cod' => 325, 'name' =>	'mapiripan', 'subregion' => 'meta_sur'],
		['deparment_id' => 50, 'cod' => 330, 'name' =>	'mesetas', 'subregion' => 'la_macarena'],
		['deparment_id' => 50, 'cod' => 350, 'name' =>	'la macarena', 'subregion' => 'la_macarena'],
		['deparment_id' => 50, 'cod' => 370, 'name' =>	'uribe', 'subregion' => 'la_macarena'],
		['deparment_id' => 50, 'cod' => 400, 'name' =>	'lejanias', 'subregion' => 'ariari'],
		['deparment_id' => 50, 'cod' => 450, 'name' =>	'puerto concordia', 'subregion' => 'meta_sur'],
		['deparment_id' => 50, 'cod' => 568, 'name' =>	'puerto gaitan', 'subregion' => 'rio_meta'],
		['deparment_id' => 50, 'cod' => 573, 'name' =>	'puerto lopez', 'subregion' => 'rio_meta'],
		['deparment_id' => 50, 'cod' => 577, 'name' =>	'puerto lleras', 'subregion' => 'ariari'],
		['deparment_id' => 50, 'cod' => 590, 'name' =>	'puerto rico', 'subregion' => 'meta_sur'],
		['deparment_id' => 50, 'cod' => 606, 'name' =>	'restrepo', 'subregion' => 'area_metropolitana'],
		['deparment_id' => 50, 'cod' => 680, 'name' =>	'san carlos de guaroa', 'subregion' => 'piedemonte'],
		['deparment_id' => 50, 'cod' => 683, 'name' =>	'san juan de arama', 'subregion' => 'ariari'],
		['deparment_id' => 50, 'cod' => 686, 'name' =>	'san juanito', 'subregion' => 'area_metropolitana'],
		['deparment_id' => 50, 'cod' => 689, 'name' =>	'san martin', 'subregion' => 'ariari'],
		['deparment_id' => 50, 'cod' => 711, 'name' =>	'vistahermosa', 'subregion' => 'la_macarena'],
		['deparment_id' => 52, 'cod' => 1, 'name' =>	'pasto'],
		['deparment_id' => 52, 'cod' => 19, 'name' =>	'alban'],
		['deparment_id' => 52, 'cod' => 22, 'name' =>	'aldana'],
		['deparment_id' => 52, 'cod' => 36, 'name' =>	'ancuya'],
		['deparment_id' => 52, 'cod' => 51, 'name' =>	'arboleda'],
		['deparment_id' => 52, 'cod' => 79, 'name' =>	'barbacoas'],
		['deparment_id' => 52, 'cod' => 83, 'name' =>	'belen'],
		['deparment_id' => 52, 'cod' => 110, 'name' =>	'buesaco'],
		['deparment_id' => 52, 'cod' => 203, 'name' =>	'colon'],
		['deparment_id' => 52, 'cod' => 207, 'name' =>	'consaca'],
		['deparment_id' => 52, 'cod' => 210, 'name' =>	'contadero'],
		['deparment_id' => 52, 'cod' => 215, 'name' =>	'cordoba'],
		['deparment_id' => 52, 'cod' => 224, 'name' =>	'cuaspud'],
		['deparment_id' => 52, 'cod' => 227, 'name' =>	'cumbal'],
		['deparment_id' => 52, 'cod' => 233, 'name' =>	'cumbitara'],
		['deparment_id' => 52, 'cod' => 240, 'name' =>	'chachagsi'],
		['deparment_id' => 52, 'cod' => 250, 'name' =>	'el charco'],
		['deparment_id' => 52, 'cod' => 254, 'name' =>	'el peñol'],
		['deparment_id' => 52, 'cod' => 256, 'name' =>	'el rosario'],
		['deparment_id' => 52, 'cod' => 258, 'name' =>	'el tablon de gomez'],
		['deparment_id' => 52, 'cod' => 260, 'name' =>	'el tambo'],
		['deparment_id' => 52, 'cod' => 287, 'name' =>	'funes'],
		['deparment_id' => 52, 'cod' => 317, 'name' =>	'guachucal'],
		['deparment_id' => 52, 'cod' => 320, 'name' =>	'guaitarilla'],
		['deparment_id' => 52, 'cod' => 323, 'name' =>	'gualmatan'],
		['deparment_id' => 52, 'cod' => 352, 'name' =>	'iles'],
		['deparment_id' => 52, 'cod' => 354, 'name' =>	'imues'],
		['deparment_id' => 52, 'cod' => 356, 'name' =>	'ipiales'],
		['deparment_id' => 52, 'cod' => 378, 'name' =>	'la cruz'],
		['deparment_id' => 52, 'cod' => 381, 'name' =>	'la florida'],
		['deparment_id' => 52, 'cod' => 385, 'name' =>	'la llanada'],
		['deparment_id' => 52, 'cod' => 390, 'name' =>	'la tola'],
		['deparment_id' => 52, 'cod' => 399, 'name' =>	'la union'],
		['deparment_id' => 52, 'cod' => 405, 'name' =>	'leiva'],
		['deparment_id' => 52, 'cod' => 411, 'name' =>	'linares'],
		['deparment_id' => 52, 'cod' => 418, 'name' =>	'los andes'],
		['deparment_id' => 52, 'cod' => 427, 'name' =>	'magsi'],
		['deparment_id' => 52, 'cod' => 435, 'name' =>	'mallama'],
		['deparment_id' => 52, 'cod' => 473, 'name' =>	'mosquera'],
		['deparment_id' => 52, 'cod' => 480, 'name' =>	'nariño'],
		['deparment_id' => 52, 'cod' => 490, 'name' =>	'olaya herrera'],
		['deparment_id' => 52, 'cod' => 506, 'name' =>	'ospina'],
		['deparment_id' => 52, 'cod' => 520, 'name' =>	'francisco pizarro'],
		['deparment_id' => 52, 'cod' => 540, 'name' =>	'policarpa'],
		['deparment_id' => 52, 'cod' => 560, 'name' =>	'potosi'],
		['deparment_id' => 52, 'cod' => 565, 'name' =>	'providencia'],
		['deparment_id' => 52, 'cod' => 573, 'name' =>	'puerres'],
		['deparment_id' => 52, 'cod' => 585, 'name' =>	'pupiales'],
		['deparment_id' => 52, 'cod' => 612, 'name' =>	'ricaurte'],
		['deparment_id' => 52, 'cod' => 621, 'name' =>	'roberto payan'],
		['deparment_id' => 52, 'cod' => 678, 'name' =>	'samaniego'],
		['deparment_id' => 52, 'cod' => 683, 'name' =>	'sandona'],
		['deparment_id' => 52, 'cod' => 685, 'name' =>	'san bernardo'],
		['deparment_id' => 52, 'cod' => 687, 'name' =>	'san lorenzo'],
		['deparment_id' => 52, 'cod' => 693, 'name' =>	'san pablo'],
		['deparment_id' => 52, 'cod' => 694, 'name' =>	'san pedro de cartago'],
		['deparment_id' => 52, 'cod' => 696, 'name' =>	'santa barbara'],
		['deparment_id' => 52, 'cod' => 699, 'name' =>	'santacruz'],
		['deparment_id' => 52, 'cod' => 720, 'name' =>	'sapuyes'],
		['deparment_id' => 52, 'cod' => 786, 'name' =>	'taminango'],
		['deparment_id' => 52, 'cod' => 788, 'name' =>	'tangua'],
		['deparment_id' => 52, 'cod' => 835, 'name' =>	'san andres de tumaco'],
		['deparment_id' => 52, 'cod' => 838, 'name' =>	'tuquerres'],
		['deparment_id' => 52, 'cod' => 885, 'name' =>	'yacuanquer'],
		['deparment_id' => 54, 'cod' => 1, 'name' =>	'cucuta'],
		['deparment_id' => 54, 'cod' => 3, 'name' =>	'abrego'],
		['deparment_id' => 54, 'cod' => 51, 'name' =>	'arboledas'],
		['deparment_id' => 54, 'cod' => 99, 'name' =>	'bochalema'],
		['deparment_id' => 54, 'cod' => 109, 'name' =>	'bucarasica'],
		['deparment_id' => 54, 'cod' => 125, 'name' =>	'cacota'],
		['deparment_id' => 54, 'cod' => 128, 'name' =>	'cachira'],
		['deparment_id' => 54, 'cod' => 172, 'name' =>	'chinacota'],
		['deparment_id' => 54, 'cod' => 174, 'name' =>	'chitaga'],
		['deparment_id' => 54, 'cod' => 206, 'name' =>	'convencion'],
		['deparment_id' => 54, 'cod' => 223, 'name' =>	'cucutilla'],
		['deparment_id' => 54, 'cod' => 239, 'name' =>	'durania'],
		['deparment_id' => 54, 'cod' => 245, 'name' =>	'el carmen'],
		['deparment_id' => 54, 'cod' => 250, 'name' =>	'el tarra'],
		['deparment_id' => 54, 'cod' => 261, 'name' =>	'el zulia'],
		['deparment_id' => 54, 'cod' => 313, 'name' =>	'gramalote'],
		['deparment_id' => 54, 'cod' => 344, 'name' =>	'hacari'],
		['deparment_id' => 54, 'cod' => 347, 'name' =>	'herran'],
		['deparment_id' => 54, 'cod' => 377, 'name' =>	'labateca'],
		['deparment_id' => 54, 'cod' => 385, 'name' =>	'la esperanza'],
		['deparment_id' => 54, 'cod' => 398, 'name' =>	'la playa'],
		['deparment_id' => 54, 'cod' => 405, 'name' =>	'los patios'],
		['deparment_id' => 54, 'cod' => 418, 'name' =>	'lourdes'],
		['deparment_id' => 54, 'cod' => 480, 'name' =>	'mutiscua'],
		['deparment_id' => 54, 'cod' => 498, 'name' =>	'ocaña'],
		['deparment_id' => 54, 'cod' => 518, 'name' =>	'pamplona'],
		['deparment_id' => 54, 'cod' => 520, 'name' =>	'pamplonita'],
		['deparment_id' => 54, 'cod' => 553, 'name' =>	'puerto santander'],
		['deparment_id' => 54, 'cod' => 599, 'name' =>	'ragonvalia'],
		['deparment_id' => 54, 'cod' => 660, 'name' =>	'salazar'],
		['deparment_id' => 54, 'cod' => 670, 'name' =>	'san calixto'],
		['deparment_id' => 54, 'cod' => 673, 'name' =>	'san cayetano'],
		['deparment_id' => 54, 'cod' => 680, 'name' =>	'santiago'],
		['deparment_id' => 54, 'cod' => 720, 'name' =>	'sardinata'],
		['deparment_id' => 54, 'cod' => 743, 'name' =>	'silos'],
		['deparment_id' => 54, 'cod' => 800, 'name' =>	'teorama'],
		['deparment_id' => 54, 'cod' => 810, 'name' =>	'tibu'],
		['deparment_id' => 54, 'cod' => 820, 'name' =>	'toledo'],
		['deparment_id' => 54, 'cod' => 871, 'name' =>	'villa caro'],
		['deparment_id' => 54, 'cod' => 874, 'name' =>	'villa del rosario'],
		['deparment_id' => 63, 'cod' => 1, 'name' =>	'armenia'],
		['deparment_id' => 63, 'cod' => 111, 'name' =>	'buenavista'],
		['deparment_id' => 63, 'cod' => 130, 'name' =>	'calarca'],
		['deparment_id' => 63, 'cod' => 190, 'name' =>	'circasia'],
		['deparment_id' => 63, 'cod' => 212, 'name' =>	'cordoba'],
		['deparment_id' => 63, 'cod' => 272, 'name' =>	'filandia'],
		['deparment_id' => 63, 'cod' => 302, 'name' =>	'genova'],
		['deparment_id' => 63, 'cod' => 401, 'name' =>	'la tebaida'],
		['deparment_id' => 63, 'cod' => 470, 'name' =>	'montenegro'],
		['deparment_id' => 63, 'cod' => 548, 'name' =>	'pijao'],
		['deparment_id' => 63, 'cod' => 594, 'name' =>	'quimbaya'],
		['deparment_id' => 63, 'cod' => 690, 'name' =>	'salento'],
		['deparment_id' => 66, 'cod' => 1, 'name' =>	'pereira'],
		['deparment_id' => 66, 'cod' => 45, 'name' =>	'apia'],
		['deparment_id' => 66, 'cod' => 75, 'name' =>	'balboa'],
		['deparment_id' => 66, 'cod' => 88, 'name' =>	'belen de umbria'],
		['deparment_id' => 66, 'cod' => 170, 'name' =>	'dosquebradas'],
		['deparment_id' => 66, 'cod' => 318, 'name' =>	'guatica'],
		['deparment_id' => 66, 'cod' => 383, 'name' =>	'la celia'],
		['deparment_id' => 66, 'cod' => 400, 'name' =>	'la virginia'],
		['deparment_id' => 66, 'cod' => 440, 'name' =>	'marsella'],
		['deparment_id' => 66, 'cod' => 456, 'name' =>	'mistrato'],
		['deparment_id' => 66, 'cod' => 572, 'name' =>	'pueblo rico'],
		['deparment_id' => 66, 'cod' => 594, 'name' =>	'quinchia'],
		['deparment_id' => 66, 'cod' => 682, 'name' =>	'santa rosa de cabal'],
		['deparment_id' => 66, 'cod' => 687, 'name' =>	'santuario'],
		['deparment_id' => 68, 'cod' => 1, 'name' =>	'bucaramanga'],
		['deparment_id' => 68, 'cod' => 13, 'name' =>	'aguada'],
		['deparment_id' => 68, 'cod' => 20, 'name' =>	'albania'],
		['deparment_id' => 68, 'cod' => 51, 'name' =>	'aratoca'],
		['deparment_id' => 68, 'cod' => 77, 'name' =>	'barbosa'],
		['deparment_id' => 68, 'cod' => 79, 'name' =>	'barichara'],
		['deparment_id' => 68, 'cod' => 81, 'name' =>	'barrancabermeja'],
		['deparment_id' => 68, 'cod' => 92, 'name' =>	'betulia'],
		['deparment_id' => 68, 'cod' => 101, 'name' =>	'bolivar'],
		['deparment_id' => 68, 'cod' => 121, 'name' =>	'cabrera'],
		['deparment_id' => 68, 'cod' => 132, 'name' =>	'california'],
		['deparment_id' => 68, 'cod' => 147, 'name' =>	'capitanejo'],
		['deparment_id' => 68, 'cod' => 152, 'name' =>	'carcasi'],
		['deparment_id' => 68, 'cod' => 160, 'name' =>	'cepita'],
		['deparment_id' => 68, 'cod' => 162, 'name' =>	'cerrito'],
		['deparment_id' => 68, 'cod' => 167, 'name' =>	'charala'],
		['deparment_id' => 68, 'cod' => 169, 'name' =>	'charta'],
		['deparment_id' => 68, 'cod' => 176, 'name' =>	'chima'],
		['deparment_id' => 68, 'cod' => 179, 'name' =>	'chipata'],
		['deparment_id' => 68, 'cod' => 190, 'name' =>	'cimitarra'],
		['deparment_id' => 68, 'cod' => 207, 'name' =>	'concepcion'],
		['deparment_id' => 68, 'cod' => 209, 'name' =>	'confines'],
		['deparment_id' => 68, 'cod' => 211, 'name' =>	'contratacion'],
		['deparment_id' => 68, 'cod' => 217, 'name' =>	'coromoro'],
		['deparment_id' => 68, 'cod' => 229, 'name' =>	'curiti'],
		['deparment_id' => 68, 'cod' => 235, 'name' =>	'el carmen de chucuri'],
		['deparment_id' => 68, 'cod' => 245, 'name' =>	'el guacamayo'],
		['deparment_id' => 68, 'cod' => 250, 'name' =>	'el peñon'],
		['deparment_id' => 68, 'cod' => 255, 'name' =>	'el playon'],
		['deparment_id' => 68, 'cod' => 264, 'name' =>	'encino'],
		['deparment_id' => 68, 'cod' => 266, 'name' =>	'enciso'],
		['deparment_id' => 68, 'cod' => 271, 'name' =>	'florian'],
		['deparment_id' => 68, 'cod' => 276, 'name' =>	'floridablanca'],
		['deparment_id' => 68, 'cod' => 296, 'name' =>	'galan'],
		['deparment_id' => 68, 'cod' => 298, 'name' =>	'gambita'],
		['deparment_id' => 68, 'cod' => 307, 'name' =>	'giron'],
		['deparment_id' => 68, 'cod' => 318, 'name' =>	'guaca'],
		['deparment_id' => 68, 'cod' => 320, 'name' =>	'guadalupe'],
		['deparment_id' => 68, 'cod' => 322, 'name' =>	'guapota'],
		['deparment_id' => 68, 'cod' => 324, 'name' =>	'guavata'],
		['deparment_id' => 68, 'cod' => 327, 'name' =>	'gsepsa'],
		['deparment_id' => 68, 'cod' => 344, 'name' =>	'hato'],
		['deparment_id' => 68, 'cod' => 368, 'name' =>	'jesus maria'],
		['deparment_id' => 68, 'cod' => 370, 'name' =>	'jordan'],
		['deparment_id' => 68, 'cod' => 377, 'name' =>	'la belleza'],
		['deparment_id' => 68, 'cod' => 385, 'name' =>	'landazuri'],
		['deparment_id' => 68, 'cod' => 397, 'name' =>	'la paz'],
		['deparment_id' => 68, 'cod' => 406, 'name' =>	'lebrija'],
		['deparment_id' => 68, 'cod' => 418, 'name' =>	'los santos'],
		['deparment_id' => 68, 'cod' => 425, 'name' =>	'macaravita'],
		['deparment_id' => 68, 'cod' => 432, 'name' =>	'malaga'],
		['deparment_id' => 68, 'cod' => 444, 'name' =>	'matanza'],
		['deparment_id' => 68, 'cod' => 464, 'name' =>	'mogotes'],
		['deparment_id' => 68, 'cod' => 468, 'name' =>	'molagavita'],
		['deparment_id' => 68, 'cod' => 498, 'name' =>	'ocamonte'],
		['deparment_id' => 68, 'cod' => 500, 'name' =>	'oiba'],
		['deparment_id' => 68, 'cod' => 502, 'name' =>	'onzaga'],
		['deparment_id' => 68, 'cod' => 522, 'name' =>	'palmar'],
		['deparment_id' => 68, 'cod' => 524, 'name' =>	'palmas del socorro'],
		['deparment_id' => 68, 'cod' => 533, 'name' =>	'paramo'],
		['deparment_id' => 68, 'cod' => 547, 'name' =>	'piedecuesta'],
		['deparment_id' => 68, 'cod' => 549, 'name' =>	'pinchote'],
		['deparment_id' => 68, 'cod' => 572, 'name' =>	'puente nacional'],
		['deparment_id' => 68, 'cod' => 573, 'name' =>	'puerto parra'],
		['deparment_id' => 68, 'cod' => 575, 'name' =>	'puerto wilches'],
		['deparment_id' => 68, 'cod' => 615, 'name' =>	'rionegro'],
		['deparment_id' => 68, 'cod' => 655, 'name' =>	'sabana de torres'],
		['deparment_id' => 68, 'cod' => 669, 'name' =>	'san andres'],
		['deparment_id' => 68, 'cod' => 673, 'name' =>	'san benito'],
		['deparment_id' => 68, 'cod' => 679, 'name' =>	'san gil'],
		['deparment_id' => 68, 'cod' => 682, 'name' =>	'san joaquin'],
		['deparment_id' => 68, 'cod' => 684, 'name' =>	'san jose de miranda'],
		['deparment_id' => 68, 'cod' => 686, 'name' =>	'san miguel'],
		['deparment_id' => 68, 'cod' => 689, 'name' =>	'san vicente de chucuri'],
		['deparment_id' => 68, 'cod' => 705, 'name' =>	'santa barbara'],
		['deparment_id' => 68, 'cod' => 720, 'name' =>	'santa helena del opon'],
		['deparment_id' => 68, 'cod' => 745, 'name' =>	'simacota'],
		['deparment_id' => 68, 'cod' => 755, 'name' =>	'socorro'],
		['deparment_id' => 68, 'cod' => 770, 'name' =>	'suaita'],
		['deparment_id' => 68, 'cod' => 773, 'name' =>	'sucre'],
		['deparment_id' => 68, 'cod' => 780, 'name' =>	'surata'],
		['deparment_id' => 68, 'cod' => 820, 'name' =>	'tona'],
		['deparment_id' => 68, 'cod' => 855, 'name' =>	'valle de san jose'],
		['deparment_id' => 68, 'cod' => 861, 'name' =>	'velez'],
		['deparment_id' => 68, 'cod' => 867, 'name' =>	'vetas'],
		['deparment_id' => 68, 'cod' => 872, 'name' =>	'villanueva'],
		['deparment_id' => 68, 'cod' => 895, 'name' =>	'zapatoca'],
		['deparment_id' => 70, 'cod' => 1, 'name' =>	'sincelejo'],
		['deparment_id' => 70, 'cod' => 110, 'name' =>	'buenavista'],
		['deparment_id' => 70, 'cod' => 124, 'name' =>	'caimito'],
		['deparment_id' => 70, 'cod' => 204, 'name' =>	'coloso'],
		['deparment_id' => 70, 'cod' => 215, 'name' =>	'corozal'],
		['deparment_id' => 70, 'cod' => 221, 'name' =>	'coveñas'],
		['deparment_id' => 70, 'cod' => 230, 'name' =>	'chalan'],
		['deparment_id' => 70, 'cod' => 233, 'name' =>	'el roble'],
		['deparment_id' => 70, 'cod' => 235, 'name' =>	'galeras'],
		['deparment_id' => 70, 'cod' => 265, 'name' =>	'guaranda'],
		['deparment_id' => 70, 'cod' => 400, 'name' =>	'la union'],
		['deparment_id' => 70, 'cod' => 418, 'name' =>	'los palmitos'],
		['deparment_id' => 70, 'cod' => 429, 'name' =>	'majagual'],
		['deparment_id' => 70, 'cod' => 473, 'name' =>	'morroa'],
		['deparment_id' => 70, 'cod' => 508, 'name' =>	'ovejas'],
		['deparment_id' => 70, 'cod' => 523, 'name' =>	'palmito'],
		['deparment_id' => 70, 'cod' => 670, 'name' =>	'sampues'],
		['deparment_id' => 70, 'cod' => 678, 'name' =>	'san benito abad'],
		['deparment_id' => 70, 'cod' => 702, 'name' =>	'san juan de betulia'],
		['deparment_id' => 70, 'cod' => 708, 'name' =>	'san marcos'],
		['deparment_id' => 70, 'cod' => 713, 'name' =>	'san onofre'],
		['deparment_id' => 70, 'cod' => 717, 'name' =>	'san pedro'],
		['deparment_id' => 70, 'cod' => 742, 'name' =>	'san luis de since'],
		['deparment_id' => 70, 'cod' => 771, 'name' =>	'sucre'],
		['deparment_id' => 70, 'cod' => 820, 'name' =>	'santiago de tolu'],
		['deparment_id' => 70, 'cod' => 823, 'name' =>	'tolu viejo'],
		['deparment_id' => 73, 'cod' => 1, 'name' =>	'ibague'],
		['deparment_id' => 73, 'cod' => 24, 'name' =>	'alpujarra'],
		['deparment_id' => 73, 'cod' => 26, 'name' =>	'alvarado'],
		['deparment_id' => 73, 'cod' => 30, 'name' =>	'ambalema'],
		['deparment_id' => 73, 'cod' => 43, 'name' =>	'anzoategui'],
		['deparment_id' => 73, 'cod' => 55, 'name' =>	'armero'],
		['deparment_id' => 73, 'cod' => 67, 'name' =>	'ataco'],
		['deparment_id' => 73, 'cod' => 124, 'name' =>	'cajamarca'],
		['deparment_id' => 73, 'cod' => 148, 'name' =>	'carmen de apicala'],
		['deparment_id' => 73, 'cod' => 152, 'name' =>	'casabianca'],
		['deparment_id' => 73, 'cod' => 168, 'name' =>	'chaparral'],
		['deparment_id' => 73, 'cod' => 200, 'name' =>	'coello'],
		['deparment_id' => 73, 'cod' => 217, 'name' =>	'coyaima'],
		['deparment_id' => 73, 'cod' => 226, 'name' =>	'cunday'],
		['deparment_id' => 73, 'cod' => 236, 'name' =>	'dolores'],
		['deparment_id' => 73, 'cod' => 268, 'name' =>	'espinal'],
		['deparment_id' => 73, 'cod' => 270, 'name' =>	'falan'],
		['deparment_id' => 73, 'cod' => 275, 'name' =>	'flandes'],
		['deparment_id' => 73, 'cod' => 283, 'name' =>	'fresno'],
		['deparment_id' => 73, 'cod' => 319, 'name' =>	'guamo'],
		['deparment_id' => 73, 'cod' => 347, 'name' =>	'herveo'],
		['deparment_id' => 73, 'cod' => 349, 'name' =>	'honda'],
		['deparment_id' => 73, 'cod' => 352, 'name' =>	'icononzo'],
		['deparment_id' => 73, 'cod' => 408, 'name' =>	'lerida'],
		['deparment_id' => 73, 'cod' => 411, 'name' =>	'libano'],
		['deparment_id' => 73, 'cod' => 443, 'name' =>	'mariquita'],
		['deparment_id' => 73, 'cod' => 449, 'name' =>	'melgar'],
		['deparment_id' => 73, 'cod' => 461, 'name' =>	'murillo'],
		['deparment_id' => 73, 'cod' => 483, 'name' =>	'natagaima'],
		['deparment_id' => 73, 'cod' => 504, 'name' =>	'ortega'],
		['deparment_id' => 73, 'cod' => 520, 'name' =>	'palocabildo'],
		['deparment_id' => 73, 'cod' => 547, 'name' =>	'piedras'],
		['deparment_id' => 73, 'cod' => 555, 'name' =>	'planadas'],
		['deparment_id' => 73, 'cod' => 563, 'name' =>	'prado'],
		['deparment_id' => 73, 'cod' => 585, 'name' =>	'purificacion'],
		['deparment_id' => 73, 'cod' => 616, 'name' =>	'rioblanco'],
		['deparment_id' => 73, 'cod' => 622, 'name' =>	'roncesvalles'],
		['deparment_id' => 73, 'cod' => 624, 'name' =>	'rovira'],
		['deparment_id' => 73, 'cod' => 671, 'name' =>	'saldaña'],
		['deparment_id' => 73, 'cod' => 675, 'name' =>	'san antonio'],
		['deparment_id' => 73, 'cod' => 678, 'name' =>	'san luis'],
		['deparment_id' => 73, 'cod' => 686, 'name' =>	'santa isabel'],
		['deparment_id' => 73, 'cod' => 770, 'name' =>	'suarez'],
		['deparment_id' => 73, 'cod' => 854, 'name' =>	'valle de san juan'],
		['deparment_id' => 73, 'cod' => 861, 'name' =>	'venadillo'],
		['deparment_id' => 73, 'cod' => 870, 'name' =>	'villahermosa'],
		['deparment_id' => 73, 'cod' => 873, 'name' =>	'villarrica'],
		['deparment_id' => 76, 'cod' => 1, 'name' =>	'cali'],
		['deparment_id' => 76, 'cod' => 20, 'name' =>	'alcala'],
		['deparment_id' => 76, 'cod' => 36, 'name' =>	'andalucia'],
		['deparment_id' => 76, 'cod' => 41, 'name' =>	'ansermanuevo'],
		['deparment_id' => 76, 'cod' => 54, 'name' =>	'argelia'],
		['deparment_id' => 76, 'cod' => 100, 'name' =>	'bolivar'],
		['deparment_id' => 76, 'cod' => 109, 'name' =>	'buenaventura'],
		['deparment_id' => 76, 'cod' => 111, 'name' =>	'guadalajara de buga'],
		['deparment_id' => 76, 'cod' => 113, 'name' =>	'bugalagrande'],
		['deparment_id' => 76, 'cod' => 122, 'name' =>	'caicedonia'],
		['deparment_id' => 76, 'cod' => 126, 'name' =>	'calima'],
		['deparment_id' => 76, 'cod' => 130, 'name' =>	'candelaria'],
		['deparment_id' => 76, 'cod' => 147, 'name' =>	'cartago'],
		['deparment_id' => 76, 'cod' => 233, 'name' =>	'dagua'],
		['deparment_id' => 76, 'cod' => 243, 'name' =>	'el aguila'],
		['deparment_id' => 76, 'cod' => 246, 'name' =>	'el cairo'],
		['deparment_id' => 76, 'cod' => 248, 'name' =>	'el cerrito'],
		['deparment_id' => 76, 'cod' => 250, 'name' =>	'el dovio'],
		['deparment_id' => 76, 'cod' => 275, 'name' =>	'florida'],
		['deparment_id' => 76, 'cod' => 306, 'name' =>	'ginebra'],
		['deparment_id' => 76, 'cod' => 318, 'name' =>	'guacari'],
		['deparment_id' => 76, 'cod' => 364, 'name' =>	'jamundi'],
		['deparment_id' => 76, 'cod' => 377, 'name' =>	'la cumbre'],
		['deparment_id' => 76, 'cod' => 400, 'name' =>	'la union'],
		['deparment_id' => 76, 'cod' => 403, 'name' =>	'la victoria'],
		['deparment_id' => 76, 'cod' => 497, 'name' =>	'obando'],
		['deparment_id' => 76, 'cod' => 520, 'name' =>	'palmira'],
		['deparment_id' => 76, 'cod' => 563, 'name' =>	'pradera'],
		['deparment_id' => 76, 'cod' => 606, 'name' =>	'restrepo'],
		['deparment_id' => 76, 'cod' => 616, 'name' =>	'riofrio'],
		['deparment_id' => 76, 'cod' => 622, 'name' =>	'roldanillo'],
		['deparment_id' => 76, 'cod' => 670, 'name' =>	'san pedro'],
		['deparment_id' => 76, 'cod' => 736, 'name' =>	'sevilla'],
		['deparment_id' => 76, 'cod' => 823, 'name' =>	'toro'],
		['deparment_id' => 76, 'cod' => 828, 'name' =>	'trujillo'],
		['deparment_id' => 76, 'cod' => 834, 'name' =>	'tulua'],
		['deparment_id' => 76, 'cod' => 845, 'name' =>	'ulloa'],
		['deparment_id' => 76, 'cod' => 863, 'name' =>	'versalles'],
		['deparment_id' => 76, 'cod' => 869, 'name' =>	'vijes'],
		['deparment_id' => 76, 'cod' => 890, 'name' =>	'yotoco'],
		['deparment_id' => 76, 'cod' => 892, 'name' =>	'yumbo'],
		['deparment_id' => 76, 'cod' => 895, 'name' =>	'zarzal'],
		['deparment_id' => 81, 'cod' => 1, 'name' =>	'arauca'],
		['deparment_id' => 81, 'cod' => 65, 'name' =>	'arauquita'],
		['deparment_id' => 81, 'cod' => 220, 'name' =>	'cravo norte'],
		['deparment_id' => 81, 'cod' => 300, 'name' =>	'fortul'],
		['deparment_id' => 81, 'cod' => 591, 'name' =>	'puerto rondon'],
		['deparment_id' => 81, 'cod' => 736, 'name' =>	'saravena'],
		['deparment_id' => 81, 'cod' => 794, 'name' =>	'tame'],
		['deparment_id' => 85, 'cod' => 1, 'name' =>	'yopal'],
		['deparment_id' => 85, 'cod' => 10, 'name' =>	'aguazul'],
		['deparment_id' => 85, 'cod' => 15, 'name' =>	'chameza'],
		['deparment_id' => 85, 'cod' => 125, 'name' =>	'hato corozal'],
		['deparment_id' => 85, 'cod' => 136, 'name' =>	'la salina'],
		['deparment_id' => 85, 'cod' => 139, 'name' =>	'mani'],
		['deparment_id' => 85, 'cod' => 162, 'name' =>	'monterrey'],
		['deparment_id' => 85, 'cod' => 225, 'name' =>	'nunchia'],
		['deparment_id' => 85, 'cod' => 230, 'name' =>	'orocue'],
		['deparment_id' => 85, 'cod' => 250, 'name' =>	'paz de ariporo'],
		['deparment_id' => 85, 'cod' => 263, 'name' =>	'pore'],
		['deparment_id' => 85, 'cod' => 279, 'name' =>	'recetor'],
		['deparment_id' => 85, 'cod' => 300, 'name' =>	'sabanalarga'],
		['deparment_id' => 85, 'cod' => 315, 'name' =>	'sacama'],
		['deparment_id' => 85, 'cod' => 325, 'name' =>	'san luis de palenque'],
		['deparment_id' => 85, 'cod' => 400, 'name' =>	'tamara'],
		['deparment_id' => 85, 'cod' => 410, 'name' =>	'tauramena'],
		['deparment_id' => 85, 'cod' => 430, 'name' =>	'trinidad'],
		['deparment_id' => 85, 'cod' => 440, 'name' =>	'villanueva'],
		['deparment_id' => 86, 'cod' => 1, 'name' =>	'mocoa'],
		['deparment_id' => 86, 'cod' => 219, 'name' =>	'colon'],
		['deparment_id' => 86, 'cod' => 320, 'name' =>	'orito'],
		['deparment_id' => 86, 'cod' => 568, 'name' =>	'puerto asis'],
		['deparment_id' => 86, 'cod' => 569, 'name' =>	'puerto caicedo'],
		['deparment_id' => 86, 'cod' => 571, 'name' =>	'puerto guzman'],
		['deparment_id' => 86, 'cod' => 573, 'name' =>	'leguizamo'],
		['deparment_id' => 86, 'cod' => 749, 'name' =>	'sibundoy'],
		['deparment_id' => 86, 'cod' => 755, 'name' =>	'san francisco'],
		['deparment_id' => 86, 'cod' => 757, 'name' =>	'san miguel'],
		['deparment_id' => 86, 'cod' => 760, 'name' =>	'santiago'],
		['deparment_id' => 86, 'cod' => 865, 'name' =>	'valle del guamuez'],
		['deparment_id' => 86, 'cod' => 885, 'name' =>	'villagarzon'],
		['deparment_id' => 88, 'cod' => 1, 'name' =>	'san andres'],
		['deparment_id' => 88, 'cod' => 564, 'name' =>	'providencia'],
		['deparment_id' => 91, 'cod' => 1, 'name' =>	'leticia'],
		['deparment_id' => 91, 'cod' => 263, 'name' =>	'el encanto'],
		['deparment_id' => 91, 'cod' => 405, 'name' =>	'la chorrera'],
		['deparment_id' => 91, 'cod' => 407, 'name' =>	'la pedrera'],
		['deparment_id' => 91, 'cod' => 430, 'name' =>	'la victoria'],
		['deparment_id' => 91, 'cod' => 460, 'name' =>	'miriti - parana'],
		['deparment_id' => 91, 'cod' => 530, 'name' =>	'puerto alegria'],
		['deparment_id' => 91, 'cod' => 536, 'name' =>	'puerto arica'],
		['deparment_id' => 91, 'cod' => 540, 'name' =>	'puerto nariño'],
		['deparment_id' => 91, 'cod' => 669, 'name' =>	'puerto santander'],
		['deparment_id' => 91, 'cod' => 798, 'name' =>	'tarapaca'],
		['deparment_id' => 94, 'cod' => 1, 'name' =>	'inirida'],
		['deparment_id' => 94, 'cod' => 343, 'name' =>	'barranco minas'],
		['deparment_id' => 94, 'cod' => 663, 'name' =>	'mapiripana'],
		['deparment_id' => 94, 'cod' => 883, 'name' =>	'san felipe'],
		['deparment_id' => 94, 'cod' => 884, 'name' =>	'puerto colombia'],
		['deparment_id' => 94, 'cod' => 885, 'name' =>	'la guadalupe'],
		['deparment_id' => 94, 'cod' => 886, 'name' =>	'cacahual'],
		['deparment_id' => 94, 'cod' => 887, 'name' =>	'pana pana'],
		['deparment_id' => 94, 'cod' => 888, 'name' =>	'morichal'],
		['deparment_id' => 95, 'cod' => 1, 'name' =>	'san jose del guaviare'],
		['deparment_id' => 95, 'cod' => 15, 'name' =>	'calamar'],
		['deparment_id' => 95, 'cod' => 25, 'name' =>	'el retorno'],
		['deparment_id' => 95, 'cod' => 200, 'name' =>	'miraflores'],
		['deparment_id' => 97, 'cod' => 1, 'name' =>	'mitu'],
		['deparment_id' => 97, 'cod' => 161, 'name' =>	'caruru'],
		['deparment_id' => 97, 'cod' => 511, 'name' =>	'pacoa'],
		['deparment_id' => 97, 'cod' => 666, 'name' =>	'taraira'],
		['deparment_id' => 97, 'cod' => 777, 'name' =>	'papunaua'],
		['deparment_id' => 97, 'cod' => 889, 'name' =>	'yavarate'],
		['deparment_id' => 99, 'cod' => 1, 'name' =>	'puerto carreño'],
		['deparment_id' => 99, 'cod' => 524, 'name' =>	'la primavera'],
		['deparment_id' => 99, 'cod' => 624, 'name' =>	'santa rosalia'],
		['deparment_id' => 99, 'cod' => 773, 'name' =>	'cumaribo']
	];


    public function run()
    {
    	foreach ($this->municipalitiesArray as $municipality) {
    		Municipality::create($municipality);
    	}
    }
}
